/* Generated By:JavaCC: Do not edit this line. LovelaceConstants.java */

/** 
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface LovelaceConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int MAIN = 5;
  /** RegularExpression Id. */
  int LET = 6;
  /** RegularExpression Id. */
  int APAR = 7;
  /** RegularExpression Id. */
  int FPAR = 8;
  /** RegularExpression Id. */
  int BEGIN = 9;
  /** RegularExpression Id. */
  int END = 10;
  /** RegularExpression Id. */
  int PV = 11;
  /** RegularExpression Id. */
  int VIRGULA = 12;
  /** RegularExpression Id. */
  int FLOAT = 13;
  /** RegularExpression Id. */
  int BOOL = 14;
  /** RegularExpression Id. */
  int VOID = 15;
  /** RegularExpression Id. */
  int ATR = 16;
  /** RegularExpression Id. */
  int PRINT = 17;
  /** RegularExpression Id. */
  int IF = 18;
  /** RegularExpression Id. */
  int WHILE = 19;
  /** RegularExpression Id. */
  int RETURN = 20;
  /** RegularExpression Id. */
  int SOMA = 21;
  /** RegularExpression Id. */
  int SUB = 22;
  /** RegularExpression Id. */
  int DIV = 23;
  /** RegularExpression Id. */
  int MULT = 24;
  /** RegularExpression Id. */
  int AND = 25;
  /** RegularExpression Id. */
  int OR = 26;
  /** RegularExpression Id. */
  int MAIOR = 27;
  /** RegularExpression Id. */
  int MENOR = 28;
  /** RegularExpression Id. */
  int IGUAL = 29;
  /** RegularExpression Id. */
  int READ = 30;
  /** RegularExpression Id. */
  int TRUE = 31;
  /** RegularExpression Id. */
  int FALSE = 32;
  /** RegularExpression Id. */
  int DEF = 33;
  /** RegularExpression Id. */
  int NUM = 34;
  /** RegularExpression Id. */
  int ID = 35;
  /** RegularExpression Id. */
  int NUMLITERAL = 36;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\t\"",
    "\"\\n\"",
    "\"\\r\"",
    "\"main\"",
    "\"let\"",
    "\"(\"",
    "\")\"",
    "\"begin\"",
    "\"end\"",
    "\";\"",
    "\",\"",
    "\"Float\"",
    "\"Bool\"",
    "\"Void\"",
    "\":=\"",
    "\"print\"",
    "\"if\"",
    "\"while\"",
    "\"return\"",
    "\"+\"",
    "\"-\"",
    "\"/\"",
    "\"*\"",
    "\"&&\"",
    "\"||\"",
    "\">\"",
    "\"<\"",
    "\"==\"",
    "\"read\"",
    "\"true\"",
    "\"false\"",
    "\"def\"",
    "<NUM>",
    "<ID>",
    "<NUMLITERAL>",
  };

}
